# pod-with-required-node-affinity.yaml
#
apiVersion: v1
kind: Pod
metadata:
  name: utrains
  namespace: geolocation
  labels:
   app: utrains
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: sku
            operator: In
            values:
            - small       
  containers:
    - name: utrains-app
      image: httpd

#
# This means that the pod will get scheduled ONLY
# on a node that has a sku=small label.
#
# First label one/more nodes
# we are classifying our nodes as small, medium & heavy 
# the label name is "sku" value can be "small / medium / heavy"
#
# First label nodeone.example.com as small and nodetwo as medium:
# kubectl label nodes nodeone.example.com sku=small
# kubectl label nodes nodetwo.example.com sku=medium
#
# Confirm for the labels on nodes using:
# kubectl get nodes --show-labels 
#
# create namespace geolocation -
# kubectl create namespace geolocation
#
# run the pod
# kubectl create -f pod-with-required-node-affinity.yaml
#
# check the pod
# kubectl get pods pod utrains -n geolocation -o wide
#
# get details about pod
# kubectl describe pod utrains -n geolocation
#
# check for the node where its running, it should be
# on any of the nodes with label "sku=small"
# 
# delete pod
# kubectl delete pod utrains -n geolocation
#
# delete the labels
# kubectl label node nodeone.example.com sku-
# kubectl label node nodetwo.example.com sku-
#
