# sample-pod-for-pod-affinity.yaml
#
apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: geolocation
  labels:
   app: web
spec:
  containers:
    - name: utrains-app
      image: httpd
#
# Creating a simple pod. Which has apache
# configured inside it.  
#
# create namespace geolocation 
# kubectl create namespace geolocation
#
# run the pod
# kubectl create -f sample-pod-for-pod-affinity.yaml
#
# check the pod
# kubectl get pods --namespace=geolocation
#
# get details about pod
# kubectl describe pod web --namespace=geolocation
# 
# Find the NODE, where its running.
#
