# pod-with-required-node-affinity-multiple.yaml
#
apiVersion: v1
kind: Pod
metadata:
  name: utrains2
  namespace: geolocation
  labels:
   app: utrains2
spec:
  containers:
    - name: utrains-app
      image: httpd
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: sku
            operator: In
            values:
            - heavy
            - medium

#
# First assign labels on all nodes in our cluster
# kubectl label node nodeone.example.com sku=small
# kubectl label node nodetwo.example.com sku=heavy
#
# Confirm the labels
# kubectl get nodes --show-labels
#
# Lets think we have some nodes with label small/medium/heavy
# We want this pod to be deployed on either pod having small
# OR medium label
#
# Confirm for the labels on nodes using:
#
# kubectl get nodes --show-labels 
#
# create namespace geolocation -
# kubectl create namespace geolocation
#
# run the pod
# kubectl create -f pod-with-required-node-affinity-multiple.yaml
#
# check the pod
# kubectl get pods -n geolocation -o wide
#
# get details about pod
# kubectl describe pod utrains -n geolocation
#
# check for the node where its running. It must be
# running on node having label sku=small OR sku=medium
# 
# delete pod
# kubectl delete pod utrains -n geolocation
#
# delete the labels
# kubectl label node nodeone.example.com sku-
# kubectl label node nodetwo.example.com sku-
# 
