# pod-without-node-selector.yaml
#
apiVersion: v1
kind: Pod
metadata:
  name: utrains1
  namespace: geolocation
  labels:
   app: utrains1
spec:
  containers:
    - name: utrains-app
      image: httpd

#
# Here, we are classifying our nodes as small, medium & heavy
# the label name is "sku" value can be "small / medium / heavy"
#
# Run the command to get the name of the node you will label
# kubectl get nodes
#
# Label a node as small:
# kubectl label nodes nodeone.example.com sku=small
#
# Confirm for the labels on nodes using:
#
# kubectl get nodes --show-labels | grep sku 
#
# create namespace geolocation -
# kubectl create namespace geolocation
#
# Run the pod
# kubectl create -f pod-without-node-selector.yaml
#
# check the pod
# kubectl get pods -n geolocation -o wide
#
# get details about pod, node where the pod is running
# kubectl describe pod utrains1 -n geolocation
#
# Look for: 
# Node-Selectors:  sku=small (it can be scheduled anywhere since it does not have a node selector specified)
#
# delete pod
# kubectl delete pod utrains1 -n geolocation
#
# delete the label from nodeone.example.com
# kubectl label node nodeone.example.com sku-
#
