apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-daemonset
spec:
  selector:
    matchLabels:
      tier: monitoring
      name: prometheus-exporter
  template:
    metadata:
      labels:
        tier: monitoring
        name: prometheus-exporter
    spec:
      containers:
      - name: prometheus
        image: prom/node-exporter
        ports:
        - containerPort: 80

# Daemonset to run a daemon for node monitoring using Prometheus Node Exporter
# create the object in the cluster:
## kubectl create -f my-daemonset.yaml
#
# List the daemonset as well as the pods created
## kubectl get daemonsets
## kubectl describe daemonset/prometheus-daemonset
## kubectl get pods
#
# Delete daemonset
## kubectl delete daemonset/prometheus-daemonset
