# pod-with-node-selector.yaml
#
apiVersion: v1
kind: Pod
metadata:
  name: utrains
  namespace: geolocation
  labels:
   app: utrains
spec:
  containers:
    - name: utrains-app
      image: httpd
  nodeSelector:
        sku: small 

#
# Here, we are classifying our nodes as small, medium & heavy
# the label name is "sku" value can be "small / medium / heavy"
#
# Run the command to get the name of the node you will label
# kubectl get nodes
#
# Label a node as small:
# kubectl label nodes nodeone.example.com sku=small
#
# Confirm for the labels on nodes using:
#
# kubectl get nodes --show-labels | grep sku 
#
# create namespace geolocation -
# kubectl create namespace geolocation
#
# run the pod
# kubectl create -f pod-with-node-selector.yaml
#
# check the pod
# kubectl get pods -n geolocation -o wide
#
# get details about pod
# kubectl describe pod utrains -n geolocation
#
# check for the node where its running
# Kubectl describe pod utrains -n geolocation
# Look for: 
# Node-Selectors:  sku=small 
#
# delete pod
# kubectl delete pod utrains -n geolocation
#
# delete the label from nodeone.example.com
# kubectl label node nodeone.example.com sku-
#
