apiVersion: v1
kind: Pod
metadata:
  name: utrains
  namespace: geolocation
  labels:
   app: utrains
spec:
  containers:
    - name: utrains-app
      image: httpd
#      image: 076892551558.dkr.ecr.us-east-1.amazonaws.com/geolocation_ecr_rep:latest
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
 
#
# Creating a simple pod. Which has apache
# configured inside it. Exposed port is 80 
# using TCP protocol  
#
# create namespace geolocation -
# kubectl create namespace geolocation
#
# run the pod
# kubectl create -f pod-with-port.yaml
#
# check the pod
# kubectl get pods --namespace=geolocation
#
# get details about pod
# kubectl describe pod utrains --namespace=geolocation
# 
# Find the IP address of this pod and the node where
# its running. Go to that node and do a :
# 
# curl http://ip-address-of-pod
#
# delete pod
# kubectl delete pod utrains --namespace=geolocation
#
