apiVersion: v1
kind: Pod
metadata:
  name: my-secret-pod1
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
      env:
        - name: SECRET_USERNAME # Environment variable name will get the value from the secret
          valueFrom:
            secretKeyRef:
              name: mysecret # Name of the variable from the secret
              key: username
        - name: SECRET_PASSWORD  # Environment variable name will get the value from the secret
          valueFrom:
            secretKeyRef:
              name: mysecret # Name of the variable from the secret
              key: password