# service-to-replicate.yaml
apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: webserver

# Consider this simple service
# And create a replicaset for it
